# Pytorch Basics From Scratch

In [2]:
import torch

**Initializing a Tensor**

In [3]:
a = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(type(a))
print(a.shape)
print(a.dtype)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
<class 'torch.Tensor'>
torch.Size([3, 3])
torch.int64


**Specify the type and device(cpu and gpu)**

1. By default it is on cpu mode
2. Requires Gradient parameter

In [7]:
a = torch.tensor([[1,2,3],[4,5,6],[7,8,9]], dtype = torch.float32,device="cuda")
# You can check that this tensor is assigned on gpu 

print(a)
print(a.dtype)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], device='cuda:0')
torch.float32


In [10]:
# you can set requires_grad = True for gradient calculation 
a = torch.tensor([[1,2,3],[4,5,6],[7,8,9]], dtype = torch.float32,device="cuda",requires_grad=True)
print(a)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], device='cuda:0', requires_grad=True)


 **All other options uselful**

In [13]:
print(a)
print(a.dtype)
print(a.shape)
print(a.device)
print(a.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], device='cuda:0', requires_grad=True)
torch.float32
torch.Size([3, 3])
cuda:0
True


## Other Initializations

In [17]:
a = torch.empty(size=(3,3)) # can get random values
print(a)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [18]:
a = torch.zeros((3,3))
print(a)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [19]:
a = torch.rand((3,3)) #intializes from Uniform Dist (0,1)
print(a)

tensor([[0.6751, 0.2551, 0.3238],
        [0.7656, 0.5768, 0.7872],
        [0.3295, 0.6783, 0.9264]])


In [21]:
a = torch.ones((5,5)) 
print(a)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [23]:
a = torch.eye(2,2) 
print(a)

tensor([[1., 0.],
        [0., 1.]])


In [28]:
a = torch.arange(start=1,end=10,step=2)
print(a)
a = torch.arange(start=10,end=1,step=-2)
print(a)
a = torch.linspace(start = 0.1,end = 1,steps = 10)
print(a)

tensor([1, 3, 5, 7, 9])
tensor([10,  8,  6,  4,  2])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [29]:
a = torch.empty(size=(1,5)).normal_(0,1)
print(a)
a = torch.empty(size=(1,5)).uniform_(0,10)
print(a)

tensor([[ 1.1529, -0.5646,  0.4949,  0.9286, -1.0402]])
tensor([[5.5153, 8.0597, 8.6019, 1.1750, 7.6753]])


In [31]:
a = torch.diag(torch.ones(3))
print(a)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


## Conversions of tensors to other datatypes

In [39]:
tensor = torch.arange(4)
print(tensor.bool())
print(tensor.short())
print(tensor.long()) #int64
print(tensor.half())
print(tensor.double())
print(tensor.float()) #float32

tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.], dtype=torch.float64)
tensor([0., 1., 2., 3.])


In [40]:
import numpy as np 

a = np.zeros((5,5))
tensor = torch.from_numpy((a))
print(tensor)
tensor = tensor.numpy()
print(tensor)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# Math and Comparsion Operations

In [46]:
x = torch.tensor([1,2,3])
y = torch.tensor([4,5,6])


print("Addition")
z1 = torch.empty(3)
torch.add(x,y,out=z1)
print(z1)

z2 = x+y
print(z2)

z3 = torch.add(x,y)
print(z3)


print("Subtraction")
z4 = x-y
print(z4)

Addition
tensor([5., 7., 9.])
tensor([5, 7, 9])
tensor([5, 7, 9])
Subtraction
tensor([-3, -3, -3])


### Inplace operations are always followed by an underscore

In [49]:
z4.add_(z3)
print(z4)

tensor([2, 4, 6])


### Simple Comparisons

In [53]:
print(z4>0)
print(z4)

tensor([True, True, True])
tensor([2, 4, 6])


In [56]:
# Matrix Multiplication

m1 = torch.rand(2,5)
m2 = torch.rand(5,3)

m3 = torch.mm(m1,m2)
print(m3)
m3 = m1.mm(m2)
print(m3)

tensor([[0.7192, 0.5641, 1.5940],
        [1.0107, 0.6342, 1.7847]])
tensor([[0.7192, 0.5641, 1.5940],
        [1.0107, 0.6342, 1.7847]])


In [62]:
# Matrix Exponentiation 

m = torch.arange(1,10).reshape(3,3)
m = m**2
print(m)

tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])


In [3]:
# Element wise multiplication
m = torch.arange(1,10).reshape(3,3)
n = torch.arange(1,10).reshape(3,3)

print(m*n)

tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])


## BroadCasting

In [8]:
x1 = torch.rand((5,5))
x2 = torch.rand((1,5))
print(x1-x2)

tensor([[-0.0049,  0.1531,  0.2821, -0.7700,  0.1728],
        [ 0.1597, -0.1532,  0.6292, -0.4588, -0.4357],
        [-0.0798, -0.4730,  0.1207, -0.7362,  0.5269],
        [ 0.7653, -0.7646,  0.0718, -0.0406,  0.1626],
        [ 0.2122, -0.1776,  0.4632,  0.0044, -0.1818]])


In [12]:
# clamp operaton set the values given on condition
x1 = torch.arange(1,10)
z = torch.clamp(x1,min=5)
print(z)

tensor([5, 5, 5, 5, 5, 6, 7, 8, 9])


In [16]:
batch =10 
features =25
x = torch.rand((batch,features))
print(x.shape)

torch.Size([10, 25])


In [17]:
print(x[0].shape)

torch.Size([25])


In [20]:
x1 = torch.arange(1,10)
print(x1[(x1<5)&(x1>2)])

tensor([3, 4])
